### ISSUE TITLE
Simplify type syntax in reconciliation queries

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#109]
Currently, reconciliation queries can contain "either a single type identifier or a list of type identifiers" according to the specs. That is, both of those queries are valid:
```json
{"query":"foo","type":"Q5"}
{"query":"foo","type":["Q5"]}
```

This is encoded in the JSON schema with a `union` construct.
As pointed out by @fsteeg, this is confusing, especially because the specs mention "an array of types" in the definition and then only have single types without arrays in the examples.

For services, it is annoying to parse this cleanly.

I would therefore propose to drop the first syntax above and require types to be enclosed in an array, even if there is only a single element.

**Comment by fsteeg** [comment]
Since this is indeed a breaking change, as described by @tfmorris in https://github.com/OpenRefine/OpenRefine/issues/5615#issuecomment-1424589666 and https://github.com/reconciliation-api/specs/pull/110#issuecomment-1424612780, maybe the right simplification here is to actually remove the array option? We might get rid of `type_strict` with that too (which would not be a breaking change since it was optional before).

(As to how this came up: I was mostly confused by the inconsistency of spec text and examples, the way we solved it was by technically using a single type, as I mentioned in https://github.com/OpenRefine/OpenRefine/issues/5615#issuecomment-1424496013. The array approach, even with `type_strict`, does not work for this use case.)

**Comment by wetneb** [comment]
That would also make sense, for sure.

**Comment by thadguidry** [comment]
The downside of removing client provided parameters is that clients cannot ask better questions to services in a single query (some might say this makes it more ambiguous to services, but I disagree in some cases) and thus clients might now need to perform multiple queries for each interesting type (less ambiguous since queries are now limited to a single type and no longer an array of them.)

My worry is that we are making things very narrow and limited in query scope and thus clients and users must now narrow their queries and perform more of them.  Ex. no longer allowed per spec? type: ["protein","chemical compound"]

Do others see any more downsides to this issue that removed client query capability?

**Comment by thadguidry** [comment]
@wetneb Yes exactly my point last year! Allowing services to return type hierarchy so that smart clients can allow users to see type distribution and allow them more informed decisions and even auto decisions with machine learning on the client side.  Allowing services that want to, a way to return much richer and deeper metadata about candidates when a user queries very narrowly once they know about higher types and common shared properties.  I think there's much room for improvement in initial type suggest feedback to clients, almost a back and forth refinement of some x number sample entities, and then users can perform the real narrow query with their chosen types and properties and exclusions.
