### ISSUE TITLE
Submitting multiple entity names in the same reconciliation query

### ISSUE THREAD

**Issue by wetneb** [reconciliation-api/specs#134]
When reconciling entities, it is not uncommon that I know multiple names for the entities I am looking for. For instance, a full name and an abbreviated one, or names in different languages, and so on.

At the moment, the reconciliation protocol does not provide a simple way to provide all of those names together in the same reconciliation query.

One possible workaround as a service is to offer a matching property which behaves like the supplied name, such that clients can send properties such as
```json
{
    "query": "A name for the entity",
    "properties": [
        { "pid": "name", "v": "Another name for the entity" }
    ]
}
```

The problem with this approach is that the `"pid": "name"` part is not standard: clients (and their users) need to discover those properties by themselves. For instance, in the Wikidata reconciliation endpoint, the pid which plays this role is `Len|Aen` (for labels and aliases in English) - good luck with discovering this! And it's not exactly equivalent to supplying a value in `"query"` since that matches against labels and aliases in all languages.

### Specify a standard property id for extra names

This would make it possible for clients (such as OpenRefine) to offer the matching of additional names in a clearer way.

Maybe the `query` field could be removed in that case, so that all values are supplied via the `properties` array. See #106.

### Make the `query` field accept arrays

Reconciliation queries of the form
```
{
     "query": [ "A name for the entity", "Another name for the entity" ]
}
```
could be submitted. Maybe queries with a single name should be reformulated to wrap the value in an array anyway, for consistency.

### Any other?

**Comment by osma** [comment]
We're doing reconciliation from YSO (which is trilingual, soon to be quadrilingual) to Wikidata, and it would be helpful to be able to query in multiple languages at once, as well as using both prefLabels and altLabels (and other label types as well, such as singular forms). In OpenRefine, each label type and language has its own column.

The proposed solution, a query with an array, doesn't seem ideal because it doesn't include information about languages. Something like this would be a better match for our usage:

```json
{
     "query": [ 
       { "language": "en", "values": [ "cars", "car", "automobiles", "automobile" ] },
       { "language": "fi", "values": [ "autot", "auto" ] },
       { "language": "sv", "values": [ "bilar", "bil" ] },
       { "language": "se", "values": [ "biillat", "biila" ] }
     ]
}
```

but is this adding too much complexity to the API?

As always, it would be up to the service endpoint to determine the relevant set of entities to return. In the case of Wikidata, I think that all entities that match at least one of the given labels in any language should be considered potential candidates.

**Comment by fsteeg** [comment]
In that case maybe the first proposed solution, using properties, would work better. You could omit the `query` and use the language as `pid` (or an additional `lang` field with a fixed `pid`). So your `queries` could look like this:

```
{
  "properties": [
    {"pid": "en", "v": "cars, car, automobiles, automobile"},
    {"pid": "fi", "v": "autot, auto"},
    {"pid": "sv", "v": "bilar, bil"},
    {"pid": "se", "v": "biillat, biila"},
  ]
}
```

That should be covered by the current draft (also using `lang` and a fixed `pid` instead).

Supporting an array in `v` has been discussed in #105 (and should have probably been part of #131).

**Comment by osma** [comment]
Revised example based on discussion on today's call:

```json
{
  "properties": [
    {"lang": "en", "v": [ "cars", "car", "automobiles", "automobile" ]},
    {"lang": "fi", "v": ["autot", "auto" ]},
    {"lang": "sv", "v": ["bilar", "bil" ]},
    {"lang": "se", "v": ["biillat", "biila" ]},
  ]
}
```

**Comment by thadguidry** [comment]
I think we should go for option 1: "Specify a standard property id for (extra) names"
 And I think "label" would be a fitting property ID to use for that?

**Comment by osma** [comment]
We discussed this during the meeting yesterday. The consensus there was that omitting `pid` entirely in cases like this could be used as a clue that it's up to the service to decide which properties to match against (there could be several, for example in SKOS at least prefLabels and hiddenLabels could be targeted), just like for `query` it is up to the service endpoint to decide how to actually do the matching.

There will be a PR upcoming, so that is an opportunity to continue the discussion and suggest alternatives.

**Comment by thadguidry** [comment]
OK. I have a worry here that the property mappings for labels is not considering a few extra things.  The use of `lang` itself is a property id for other services.  I was trying to explain that it itself is a property and the whole object could be called `label`.  

Client request:

label=
{"lang": "fi", "v": [ "autot", "auto" ]}

Stupid computer service:

OK do you want to match against my entities that ate indexed with prefLabels or altLabels? Maybe both?

If we were to go to the explicit level and avoid confusion for providers and clients and ease the mapping, then I would expect more rigid semantics talked about in this proposal.

properties ->label->lang:value,v:value,

But in your example we are implying a `lang,v` object is a `label` object.

Does this take away capability from clients to ask for matches where 1 `label` object should be matched with `prefLabel` only while other `label ` objects should be matched to `altLabel` ?  How can we give more power to clients for matching heuristics?

Example:

ex:fava_bean rdf:type skos:Concept;
skos:prefLabel "Fava bean"@en;
skos:altLabel "Broad bean"@en.

Would clients filter or constrain on `label` objects themselves to ask "hey only match these values in this array in English language, AND only against `prefLabel` and no `altLabel`'s? How? By inserting an extra `pid:altLabel` into the `label` object? Because outside of it would lose the mapping against each language.  Maybe a client wants `altLabel` matches only for the Finish values?

**Comment by thadguidry** [comment]
My simple point is that there's many things (subproperties) to say about a label. Basically all owl:AnnotationProperty's and rdfs:label's.  And clients will want to filter against those properties.

**Comment by osma** [comment]
I think of it this way:

* no `pid` given: let the service choose what properties to match against (just like it already does for `query`)
* explicit `pid` given: match only against that property

So if the client wants to match only against prefLabels, use `"pid": "skos:prefLabel"` or something along those lines. If the client doesn't care what label types to match against, leave `pid` unset and let the service worry about it. The spec already says that `query` should be matched against names, without specifying the details, so this is not a new requirement:

> By supplying such a string, a client intends to search for entities with similar names. The specifics of how this similarity is defined are determined by the service.
