### ISSUE TITLE
Question about suitability for autocompletion

### ISSUE THREAD

**Issue by D-Groenewegen** [reconciliation-api/specs#178]
Dear all, this may be a bit of an ill-informed question so please bear with me. 

I was entertaining the possibility of creating an implementation of this API for wikis that use Semantic MediaWiki (https://www.semantic-mediawiki.org/) so that they can make their data available for reconciliation in OpenRefine or whatever will follow in its footsteps. A lot of what the API offers also ties in with features that can be expected from a more traditional API used for autocompletion: a query is run in response to user input, a list of 'candidates' is suggested to the user, and for each entity/candidate the user may get a label, description and maybe an associated image.

In that respect, the Reconciliation API might be equally useful as an Autocomplete API for local uses, in a form or search box for instance, as well as external uses. 

On the other hand, I wonder if the Reconciliation API supports, or intends to support, other features that you might want to see from an Autocomplete API. I am thinking, in particular, of the more straightforward ability for the API to just return plain string values in direct response to a query.

Would that still be within the intended scope? So would I be wrong in trying to repurpose the Reconciliation API for the purpose of autocompletion?

(P.S. There are, of course, many other features that would not be regulated by the API anyway and are rather the preserve of JavaScript implementations, such as the use of multiple, Select2-like 'tokens' that you can drag to put them in the appropriate order, etc.)

**Comment by fsteeg** [comment]
I think the reconciliation API is very much usable for the purpose of auto-completion. In fact, the [suggest services](https://reconciliation-api.github.io/specs/draft/#suggest-services) are specifically designed for auto-completion.  Additionally, the [preview service](https://reconciliation-api.github.io/specs/draft/#preview-service) might be useful to provide little overviews for each suggestion (see this example [from our service](https://lobid.org/gnd/118624822.preview)).

**Comment by wetneb** [comment]
@D-Groenewegen an implementation of this API for Semantic MediaWiki would be fantastic! I'd be happy to help make that happen if I can.

As @fsteeg mentioned, the reconciliation protocol lets you search for things in two ways:
* by submitting reconciliation queries, which can be quite elaborate (with type filtering, additional properties, matching settings…).
* by submitting "suggest queries", which really just contain the text that the user types in the field - that's what you want to use for auto-completion

It's worth considering why those two endpoints are separate - what's the difference between the two?
* speed expectations: for auto-completion (the "suggest queries") the response needs to be very fast as it's used in an interactive way in a UI. For reconciliation, it's obviously ideal if it's also fast, but it's more acceptable to be slow because it's a longer process anyway
* search methods: for auto-completion, it's common to search for entities by prefix (since the text you have in the text box is being typed) or accept other sorts of very partial matches. For reconciliation, the expectation is that you have the entire string at your disposal and so if it only matches a tiny part of the whole name of an entity, it should likely not be ranked very high in the results
* importance of scoring and ordering of the results: it's much more critical in reconciliation (where the user should ideally be able to trust that matches scored above a certain threshold will be good) than in auto-completion (where the user will be able to pick the right match after a few tries, changing the text they have input in the field)

> I am thinking, in particular, of the more straightforward ability for the API to just return plain string values in direct response to a query.

We discussed this in our call today and we were wondering if we understood this part correctly. Do you mean that the HTTP response to an auto-completion query should contain only plain text (not wrapped in any JSON)? I would find that surprising. All of the auto-completion endpoints I have worked with had some structure in their response, so that they are able to return a list of matches, separating different fields such as identifier and name.

**Comment by D-Groenewegen** [comment]
Many thanks for your explanations, you have given me much food for thought there! 

What I would like to do is to allow the site admin to create and maintain one or multiple configuration profiles as JSON pages in the wiki. Such a profile would contain the basic ingredients needed for the API to create and run the appropriate queries and format query output. Multiple profiles could mean multiple services provided by the same wiki. In an ideal world, a single one might be preferred but the reality probably calls for some flexibility.

No doubt there will be challenges relating to the specifics of SMW, such as unresolved bugs and divergent behaviours relating to different site settings or backends (e.g. MySQL vs MySQL+Elasticsearch), but all in good time. 

> Do you mean that the HTTP response to an auto-completion query should contain only plain text (not wrapped in any JSON)?

No, the output definitely would be JSON, but in some cases, we would be merely interested in matching on and then returning a string value, typically the value of the property, rather than a corresponding entity, label, etc. That's all really. You would probably still use both an identifier and label, but they would be mostly identical. That to me sounds like it is covered by 'suggest services', without the need for any reconciliation happening.

**Comment by wetneb** [comment]
@D-Groenewegen great! That sounds all doable in my opinion.

Unless you see anything that needs to be changed in the protocol, I would propose to close this issue.

**Comment by D-Groenewegen** [comment]
Thanks, you can close this as 'resolved'.

Just to explain. I've had occasion to start work on the extension, beginning with the 'Suggest property' and 'Suggest entity' services. Unsurprisingly perhaps given the many real-world use cases for data autocompletion, there are particular needs, mostly for wiki-internal use, that I would like to address but are not currently targeted by the Reconciliation API, e.g. extending support for substring matching. Fortunately, I don't think there is anything incompatible about meeting the core requirements of the API and making additional properties and services available for other (non-OpenRefine) uses as long as the latter are made transparent as such and don't interfere.

In hindsight, the service that I had in mind does not appear to be covered by the three types of scope for 'suggest' services (property, entity and type). It would return values of a given property that represent simple strings as opposed to structured entities. It is arguable that such a service would have any place if the purpose is to reconcile data against other resources. Of course, there is nothing stopping me from creating an additional service, so I see no real conflict there.
